# Generated by Django 3.2.2 on 2021-12-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
